services:
  json-merger:
    container_name: json.merger
    build: .
    networks:
      - json.merger.net
    expose:
      - "3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/index.html"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  json.merger.net:
    name: json.merger.net

